version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeSE_tlundstr2
  gitServerName: tlundstr_git
  gitUrl: https://github.com/tlundstr/EdgeSE_tlundstr2
  gitUsername: tlundstr
  gitToken: edge.scaffolding.EdgeSE_tlundstr2.tlundstr_git.gitToken
  gitBranch: main
